local NetherBot = NetherBot

BINDING_HEADER_BUTTON_MAIN = "NetherBot-主按键"
BINDING_NAME_BUTTON_MAIN_COMMAND_FOLLOW = NetherBot.BUTTON_MAIN_TABLE.COMMAND_FOLLOW.NAME
BINDING_NAME_BUTTON_MAIN_COMMAND_FOLLOW_ONLY = NetherBot.BUTTON_MAIN_TABLE.COMMAND_FOLLOW_ONLY.NAME
BINDING_NAME_BUTTON_MAIN_COMMAND_STOP_FULLY = NetherBot.BUTTON_MAIN_TABLE.COMMAND_STOP_FULLY.NAME
BINDING_NAME_BUTTON_MAIN_COMMAND_STANDSTILL = NetherBot.BUTTON_MAIN_TABLE.COMMAND_STANDSTILL.NAME
BINDING_NAME_BUTTON_MAIN_COMMAND_NO_GOSSIP = NetherBot.BUTTON_MAIN_TABLE.COMMAND_NO_GOSSIP.NAME
BINDING_NAME_BUTTON_MAIN_HIDE = NetherBot.BUTTON_MAIN_TABLE.HIDE.NAME
BINDING_NAME_BUTTON_MAIN_SHOW = NetherBot.BUTTON_MAIN_TABLE.SHOW.NAME
BINDING_NAME_BUTTON_MAIN_RECALL = NetherBot.BUTTON_MAIN_TABLE.RECALL.NAME
BINDING_NAME_BUTTON_MAIN_RECALL_TELEPORT = NetherBot.BUTTON_MAIN_TABLE.RECALL_TELEPORT.NAME
BINDING_NAME_BUTTON_MAIN_COMMAND_WALK = NetherBot.BUTTON_MAIN_TABLE.COMMAND_WALK.NAME
BINDING_NAME_BUTTON_MAIN_COMMAND_UNBIND = NetherBot.BUTTON_MAIN_TABLE.COMMAND_UNBIND.NAME
BINDING_NAME_BUTTON_MAIN_COMMAND_REBIND = NetherBot.BUTTON_MAIN_TABLE.COMMAND_REBIND.NAME
BINDING_NAME_BUTTON_MAIN_RECALL_SPAWNS = NetherBot.BUTTON_MAIN_TABLE.RECALL_SPAWNS.NAME
BINDING_NAME_BUTTON_MAIN_INFO = NetherBot.BUTTON_MAIN_TABLE.INFO.NAME
BINDING_NAME_BUTTON_MAIN_KILL = NetherBot.BUTTON_MAIN_TABLE.KILL.NAME
BINDING_NAME_BUTTON_MAIN_VEHICLE_EJECT = NetherBot.BUTTON_MAIN_TABLE.VEHICLE_EJECT.NAME

BINDING_HEADER_BUTTON_CAST_SPELL_WARRIOR = "NetherBot-战士"
BINDING_NAME_BUTTON_CAST_SPELL_WARRIOR_J_J = NetherBot.BUTTON_CAST_SPELL_TABLE.WARRIOR.J_J.NAME
BINDING_NAME_BUTTON_CAST_SPELL_WARRIOR_Y_H = NetherBot.BUTTON_CAST_SPELL_TABLE.WARRIOR.Y_H.NAME

BINDING_HEADER_BUTTON_CAST_SPELL_PALADIN = "NetherBot-圣骑士"
BINDING_NAME_BUTTON_CAST_SPELL_PALADIN_B_H_Z_S = NetherBot.BUTTON_CAST_SPELL_TABLE.PALADIN.B_H_Z_S.NAME
BINDING_NAME_BUTTON_CAST_SPELL_PALADIN_Z_J_Z_S = NetherBot.BUTTON_CAST_SPELL_TABLE.PALADIN.Z_J_Z_S.NAME
BINDING_NAME_BUTTON_CAST_SPELL_PALADIN_X_S_Z_S = NetherBot.BUTTON_CAST_SPELL_TABLE.PALADIN.X_S_Z_S.NAME
BINDING_NAME_BUTTON_CAST_SPELL_PALADIN_Z_Y_F_Y = NetherBot.BUTTON_CAST_SPELL_TABLE.PALADIN.Z_Y_F_Y.NAME
BINDING_NAME_BUTTON_CAST_SPELL_PALADIN_S_G_D_B = NetherBot.BUTTON_CAST_SPELL_TABLE.PALADIN.S_G_D_B.NAME
BINDING_NAME_BUTTON_CAST_SPELL_PALADIN_Q_X_L_L_Z_F = NetherBot.BUTTON_CAST_SPELL_TABLE.PALADIN.Q_X_L_L_Z_F.NAME
BINDING_NAME_BUTTON_CAST_SPELL_PALADIN_Q_X_Z_H_Z_F = NetherBot.BUTTON_CAST_SPELL_TABLE.PALADIN.Q_X_Z_H_Z_F.NAME
BINDING_NAME_BUTTON_CAST_SPELL_PALADIN_Q_X_W_Z_Z_F = NetherBot.BUTTON_CAST_SPELL_TABLE.PALADIN.Q_X_W_Z_Z_F.NAME
BINDING_NAME_BUTTON_CAST_SPELL_PALADIN_Q_X_B_H_Z_F = NetherBot.BUTTON_CAST_SPELL_TABLE.PALADIN.Q_X_B_H_Z_F.NAME
BINDING_NAME_BUTTON_CAST_SPELL_PALADIN_J_S = NetherBot.BUTTON_CAST_SPELL_TABLE.PALADIN.J_S.NAME

BINDING_HEADER_BUTTON_CAST_SPELL_HUNTER = "NetherBot-猎人"
BINDING_NAME_BUTTON_CAST_SPELL_HUNTER_W_D = NetherBot.BUTTON_CAST_SPELL_TABLE.HUNTER.W_D.NAME

BINDING_HEADER_BUTTON_CAST_SPELL_ROGUE = "NetherBot-盗贼"
BINDING_NAME_BUTTON_CAST_SPELL_ROGUE_J_H_J_Q = NetherBot.BUTTON_CAST_SPELL_TABLE.ROGUE.J_H_J_Q.NAME

BINDING_HEADER_BUTTON_CAST_SPELL_PRIEST = "NetherBot-牧师"
BINDING_NAME_BUTTON_CAST_SPELL_PRIEST_Y_H_D_Y = NetherBot.BUTTON_CAST_SPELL_TABLE.PRIEST.Y_H_D_Y.NAME
BINDING_NAME_BUTTON_CAST_SPELL_PRIEST_P_F_S = NetherBot.BUTTON_CAST_SPELL_TABLE.PRIEST.P_F_S.NAME
BINDING_NAME_BUTTON_CAST_SPELL_PRIEST_F_H_S = NetherBot.BUTTON_CAST_SPELL_TABLE.PRIEST.F_H_S.NAME

BINDING_HEADER_BUTTON_CAST_SPELL_DEATH_KNIGHT = "NetherBot-死亡骑士"
BINDING_NAME_BUTTON_CAST_SPELL_DEATH_KNIGHT_K_L = NetherBot.BUTTON_CAST_SPELL_TABLE.DEATH_KNIGHT.K_L.NAME

BINDING_HEADER_BUTTON_CAST_SPELL_SHAMAN = "NetherBot-萨满"
BINDING_NAME_BUTTON_CAST_SPELL_SHAMAN_X_Z_Z_H = NetherBot.BUTTON_CAST_SPELL_TABLE.SHAMAN.X_Z_Z_H.NAME

BINDING_HEADER_BUTTON_CAST_SPELL_MAGE = "NetherBot-法师"
BINDING_NAME_BUTTON_CAST_SPELL_MAGE_H_L_S = NetherBot.BUTTON_CAST_SPELL_TABLE.MAGE.H_L_S.NAME
BINDING_NAME_BUTTON_CAST_SPELL_MAGE_M_F_Y_Z = NetherBot.BUTTON_CAST_SPELL_TABLE.MAGE.M_F_Y_Z.NAME
BINDING_NAME_BUTTON_CAST_SPELL_MAGE_M_F_Z_X = NetherBot.BUTTON_CAST_SPELL_TABLE.MAGE.M_F_Z_X.NAME

BINDING_HEADER_BUTTON_CAST_SPELL_DRUID = "NetherBot-德鲁伊"
BINDING_NAME_BUTTON_CAST_SPELL_DRUID_F_S = NetherBot.BUTTON_CAST_SPELL_TABLE.DRUID.F_S.NAME
BINDING_NAME_BUTTON_CAST_SPELL_DRUID_Q_S_H_S = NetherBot.BUTTON_CAST_SPELL_TABLE.DRUID.Q_S_H_S.NAME